name: couldai_user_app
description: "A modern social networking app for Pickleball enthusiasts."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  provider: ^6.1.2

flutter:
  uses-material-design: true
  fonts:
    - family: SF Pro
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700
  assets:
    - fonts/