// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: fzvnnbeixhkjeesvxslg

class SupabaseConfig {
  static const String supabaseUrl = 'https://fzvnnbeixhkjeesvxslg.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6dm5uYmVpeGhramVlc3Z4c2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzNjUyODAsImV4cCI6MjA4ODk0MTI4MH0.a_9PmZ2iZBqL5EGxxwd_8Fo3piMkJ_1N1nMmZF1RPMQ';
}
