// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: bwuwsaongwpgpfvqoeyq

class SupabaseConfig {
  static const String supabaseUrl = 'https://bwuwsaongwpgpfvqoeyq.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3dXdzYW9uZ3dwZ3BmdnFvZXlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyMjMzMTcsImV4cCI6MjA4ODc5OTMxN30.nKCVix0KFs044baE7AAWq4OC8SC-yFalIKzmMlptNIA';
}
